{% set name = "opsgenie-sdk" %}
{% set version = "2.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opsgenie-sdk-{{ version }}.tar.gz
  sha256: c38a2f0c7acbcbeb9202ced80ec857b5eda2d99919392fed4083bdfa7be32669

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - certifi
    - python-dateutil
    - setuptools >=21.0.0
    - six >=1.10
    - tenacity >=5.0.4
    - urllib3 >=1.26.5

test:
  imports:
    - opsgenie_sdk
    - opsgenie_sdk.api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opsgenie/opsgenie-python-sdk
  summary: Python SDK for Opsgenie REST API
  dev_url: https://github.com/opsgenie/opsgenie-python-sdk
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
